apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-hello-world
spec:
  selector:
    matchLabels:
      app: sample-hello-world
  template:
    metadata:
      labels:
        app: sample-hello-world
    spec:
      containers:
      - name: sample-hello-world
        image: quay.io/openshift-knative/helloworld-go:ppc64le
        ports:
        - containerPort: 8080
          name: http
